table 'gold fact_teamfights'
	lineageTag: cd5c8f16-5dc5-48e8-93f9-3957a20690a1

	column match_id
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: f48d854f-d237-48be-9485-7a140e9d39d5
		summarizeBy: none
		sourceColumn: match_id

		annotation SummarizationSetBy = Automatic

	column teamfight_id
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 8dd19828-6bf7-4d98-9d70-2ef76559ccc3
		summarizeBy: none
		sourceColumn: teamfight_id

		annotation SummarizationSetBy = Automatic

	column start_time
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: df9ac8fe-ebc3-4dca-ac89-c3659fc67906
		summarizeBy: sum
		sourceColumn: start_time

		annotation SummarizationSetBy = Automatic

	column end_time
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8c808c1d-5fb6-45a4-8781-46f8e5014afa
		summarizeBy: sum
		sourceColumn: end_time

		annotation SummarizationSetBy = Automatic

	column last_death
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ee98faed-b0de-49d0-be2b-93d7e81675a2
		summarizeBy: sum
		sourceColumn: last_death

		annotation SummarizationSetBy = Automatic

	column start_min
		dataType: double
		sourceProviderType: decimal
		lineageTag: a462c3cd-b0b0-4143-9fde-478c5113a90a
		summarizeBy: sum
		sourceColumn: start_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column end_min
		dataType: double
		sourceProviderType: decimal
		lineageTag: 55831d10-4b45-4f6a-8803-00226e2e8302
		summarizeBy: sum
		sourceColumn: end_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column last_death_min
		dataType: double
		sourceProviderType: decimal
		lineageTag: 00a378ee-d1d2-44a5-b173-5d7585bd0afc
		summarizeBy: sum
		sourceColumn: last_death_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deaths
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4cb68c50-33cc-42a6-82cf-71edcae9107d
		summarizeBy: sum
		sourceColumn: deaths

		annotation SummarizationSetBy = Automatic

	column duration_sec
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 0f533bdd-cc1f-4f8c-91e5-c9741de4f275
		summarizeBy: sum
		sourceColumn: duration_sec

		annotation SummarizationSetBy = Automatic

	column duration_min
		dataType: double
		sourceProviderType: decimal
		lineageTag: 6e974f9d-13eb-41e3-9aab-996016b02213
		summarizeBy: sum
		sourceColumn: duration_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column loaded_at
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 11e9f7b4-46a1-472d-bafe-3fcde8f1db6f
		summarizeBy: none
		sourceColumn: loaded_at

		annotation SummarizationSetBy = Automatic

	partition 'gold fact_teamfights' = m
		mode: directQuery
		source =
				let
				    Source = PostgreSQL.Database("localhost", "dota"),
				    gold_fact_teamfights = Source{[Schema="gold",Item="fact_teamfights"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(gold_fact_teamfights,{"players"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

